name: lab_instrument_identifier
description: Identificador de instrumentos de laboratorio.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.4.0
  riverpod: 2.4.0
  go_router: ^17.0.0
  camera: ^0.11.2+1
  logger: ^2.7.0
  permission_handler: ^12.0.1
  tflite_flutter: ^0.12.1
  image: ^4.0.20
  flutter_image_compress: ^2.4.0
  path_provider: ^2.0.15
  sqflite: ^2.2.0
  path: ^1.8.3
  json_annotation: ^4.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/data/
    - assets/imagenes/
    - assets/animations/
